name: lumiere_note_sp
description: Lumiere Note Sp App Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <=3.3.10"

dependencies:
  auto_route: ^5.0.4
  badges: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.0
  dio: ^4.0.6
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  gql: ^0.14.0
  path_provider: ^2.0.12
  hive: ^2.2.3
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  youtube_player_iframe: ^4.0.4
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  permission_handler: ^10.0.0
  persistent_bottom_nav_bar: ^5.0.2
  pull_to_refresh: ^2.0.0
  retrofit: '>=3.0.0 <4.0.0'
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  just_the_tooltip: ^0.0.12
  percent_indicator: ^4.2.2
  easy_localization: ^3.0.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.11
  flutter_flavorizr: ^2.1.3
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "LumiereNoteSp（Dev）"
      android:
        applicationId: "com.lumierenotesp.app.jp.dev"
      ios:
        bundleId: "com.lumierenotesp.app.jp.dev"

    staging:
      app:
        name: "LumiereNoteSp（Stg）"
      android:
        applicationId: "com.lumierenotesp.app.jp.stg"
      ios:
        bundleId: "com.lumierenotesp.app.jp.stg"

    production:
      app:
        name: "LumiereNoteSp"
      android:
        applicationId: "com.lumierenotesp.app.jp"
      ios:
        bundleId: "com.lumierenotesp.app.jp"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true

  fonts:
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/SF-ProText-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/svg/
    - assets/icons/
    - assets/translations/
